### ISSUE TITLE
You can unload logs that are under other logs in the logspace

### ISSUE THREAD

**Issue by gaviarctica** [gaviarctica/forestry-game-frontend#19] opened 2017-12-04 19:00 UTC
Way to reproduce the bug:
1. Go to the striproad map (straight one with 4 unloading stations)
2. Drive down and pick up all the brown and yellow logs on the way
3. In the end unload 3 yellow logs to the right deposit and 2 brown logs to the left leaving 2 brown logs to the logspace
4. Pick up the orange log behind you
5. You can still unload the brown logs that are under the orange log in your logspace

**Comment by kavaari** [comment] 2017-12-16 20:18
should be fixed now

**Comment by nime88** [comment] 2017-12-18 09:50
Closing issue since this can't be reproduced anymore

**Closed as completed by nime88** 2017-12-18 09:50 UTC
